language: node_js

sudo: false

node_js:
  - "9.11.1"
services:
  - mongodb
env:
  - PIPERMAIL_DATABASE="mongodb://localhost/tempjs" PIPERMAIL_SOURCE="https://mail.mozilla.org/pipermail/es-discuss/"
before_script:
  - sleep 15

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
    node_js: 9.11.1
